kind: Pod
apiVersion: v1
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: course
        value: DevOps
      - name: duration
        value: 40-hours
      - name: Lecturer
        value: Raghu Kadapala
    